# Site settings
title: Waterhackweek 2020
email: fwi@uw.edu
description: With feedback from the community and updated recommendations from the <br>
             University of Washington and Seattle & King County Public Health,<br>
             Waterhackweek leaders have decided to postpone Waterhackweek 2020 to August 31-September 4 <br>
             because of the novel coronavirus (COVID-19) outbreak.<br>
             We deeply appreciate your input, patience, and flexibility in this difficult situation. <br>
             See the latest Waterhackweek COVID-19 Updates here.
             #Workshop On Water Data Science <br>
             #University of Washington eScience Institute <br>
             #March 23-27, 2020<br>
             #Registration closes January 5, 2020<br>
             #Applications will open September, 2019  <br>
            # Open water <br> <br>
             #<a href="https://www.jotform.com/build/82396990821165/">here</a>
  #click <a href="https://www.jotform.com/build/82396990821165/">here</a> <br>
             #Announcements will be made shortly.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/waterhackweek
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url: https://waterhackweek2019.slack.com
twitter_url:
email_url: fwi@uw.edu

# Build settings
markdown: kramdown

